### ISSUE TITLE
Cannot `npm install` package because invalid peer dependencies

### ISSUE THREAD

**Issue by duckpunch** [mkay581/build-tools#4]
Steps I used:

1. Checked out repo
2. `npm install` - got an error.
3. `npm list` for more details.

Slightly more details here: https://github.com/mkay581/scroll-js/pull/6#issuecomment-125766526

My environment:
```
$ npm --version
2.11.2
$ node --version
v0.12.5
```

The error:

`npm ERR! peer invalid: phantomjs@1.9.17 /path/to/build-tools/node_modules/phantomjs`

**Comment by mkay581** [comment]
Thanks, this uses an older version of mocha-phantomjs package which requires a phantomjs explicit dependency no later than version 1.9.15. but you ended up installing the latest (1.9.17), which gives that error.

To fix this, I could have just locked the version of phantomjs to 1.9.15, but instead of doing that, I thought it would be more efficient to just remove the phantomjs dep altogether. Since this package doesnt need it explicitly anyway, and the new version of mocha-phantomjs no longer requires explicit phantomjs packages.Your issue here is similar to [this issue](https://github.com/eslint/eslint/issues/3021).

Anyway, the fix can be found in latest 1.6.0 of this package which is now published. I'll hop over and add it to the scroll-js package so that it uses it.

**Comment by mkay581** [comment]
FYI, here is the commit that fixes this: c3550c2838aa1b17f739b6d24f6904449ba02845

**Comment by duckpunch** [comment]
Nice.

Thanks!

**Comment by mkay581** [comment]
did this fix your npm install issue? if so, i'll close.

**Comment by duckpunch** [comment]
Yep, looks like it did.  Thanks!

**Comment by mkay581** [comment]
cool thanks
